<center>
	<b><u>DB Credentials</u></b>
	<br /><br />
	<table>
		<tr>
			<td>
				Host:
			</td>
			<td>
				<input type="text" id="dbHost" value="<?=$dbConfig['dbHost'];?>" />
			</td>
		</tr>
		<tr>
			<td>
				DB name:
			</td>
			<td>
				<input type="text" id="dbName" value="<?=$dbConfig['dbName'];?>" />
			</td>
		</tr>
		<tr>
			<td>
				DB User:
			</td>
			<td>
				<input type="text" id="dbUser" value="<?=$dbConfig['dbUser'];?>" />
			</td>
		</tr>
		<tr>
			<td>
				Password:
			</td>
			<td>
				<input type="text" id="dbPass" value="<?=$dbConfig['dbPass'];?>" />
			</td>
		</tr>
		<tr>
			<td>
			
			</td>
			<td>
				<center>
					<input class="btn" type="submit" value="Save" />
					<input class="btn" type="submit" value="Test" />
				</center>
			</td>
		</tr>
	<table>
<center>