<script type="text/javascript">
var Config = {
	'saveConfig' : function()
	{
		$("#configFeeder").html("Saving...");		
		var postStr = '';
		postStr += 'dbHost=' + $("#dbHost").val();
		postStr += '&dbName=' + $("#dbName").val();
		postStr += '&dbUser=' + $("#dbUser").val();
		postStr += '&dbPass=' + $("#dbPass").val();
		
		$.ajax({
			type : 'POST',
			url : '<?=$baseUrl;?>/Hanuman/config/save',
			data : postStr,
			success : function(jsonObj)
			{
				if (jsonObj.success)
				{
					$("#configFeeder").html("Configuration saved");		
				}
				else
				{
					$('#configFeeder').html(jsonObj.message);		
				}
			}
		});
	},
	'testDbCon' : function()
	{
		$("#configFeeder").html("Testing...");		
		$.ajax({
			type : 'POST',
			url : '<?=$baseUrl;?>/Hanuman/config/testdbcon',
			data : '',
			success : function(jsonObj)
			{
				if (jsonObj.success)
				{
					$("#configFeeder").html("Good to go");		
				}
				else
				{
					$('#configFeeder').html(jsonObj.message);		
				}
			}
		});
	}
};
</script>
<center>
	<b><u>DB Credentials</u></b>
	<br /><br />
	<table>
		<tr>
			<td>
				Host:
			</td>
			<td>
				<input type="text" id="dbHost" value="<?=$dbConfig['dbHost'];?>" />
			</td>
		</tr>
		<tr>
			<td>
				DB name:
			</td>
			<td>
				<input type="text" id="dbName" value="<?=$dbConfig['dbName'];?>" />
			</td>
		</tr>
		<tr>
			<td>
				DB User:
			</td>
			<td>
				<input type="text" id="dbUser" value="<?=$dbConfig['dbUser'];?>" />
			</td>
		</tr>
		<tr>
			<td>
				Password:
			</td>
			<td>
				<input type="text" id="dbPass" value="<?=$dbConfig['dbPass'];?>" />
			</td>
		</tr>
		<tr>
			<td>
			
			</td>
			<td>
				<center>
					<input onClick="Config.saveConfig();" class="btn" type="submit" value="Save" />
					<input onClick="Config.testDbCon();" class="btn" type="submit" value="Test DB Connection" />
				</center>
			</td>
		</tr>
	<table>
	<div id="configFeeder"></div>
<center>