<script type="text/javascript">
var selectedModule = '<?=$selectedModule;?>';
var Module = {
	'fields' : [],
	'crudController' : '',
	'getControllers' : function()
	{
		$.ajax({
			type : 'POST',
			url : '<?=$baseUrl;?>/Hanuman/modules/getcontrollers',
			data : 'moduleName=' + selectedModule,
			success : function(jsonObj)
			{
				if (jsonObj.success)
				{
					$("#controllerSelect").empty();
					for (var i = 0; i < jsonObj.data.length; i++)
					{
						$("#controllerSelect").append("<option value='"+ jsonObj.data[i] +"'>"+ jsonObj.data[i] +"</option>");
					}
					$('#controllersFeeder').html('<br />');
				}
				else
				{
					$('#controllersFeeder').html(jsonObj.message);		
				}
			}
		});
	},
	'getModels' : function()
	{
		$.ajax({
			type : 'POST',
			url : '<?=$baseUrl;?>/Hanuman/modules/getmodels',
			data : 'moduleName=' + selectedModule,
			success : function(jsonObj)
			{
				if (jsonObj.success)
				{
					$("#modelsSelect").empty();
					for (var i = 0; i < jsonObj.data.length; i++)
					{
						$("#modelsSelect").append("<option value='"+ jsonObj.data[i] +"'>"+ jsonObj.data[i] +"</option>");
					}
					$('#modelsFeeder').html('<br />');
				}
				else
				{
					$('#modelsFeeder').html(jsonObj.message);		
				}
			}
		});
	},	
	'addController' : function()
	{
		if ($("#crud").is(":checked"))
		{
			Module.fields = [{'name' : 'ID', 'type' : 'INT(255)'}];
			Module.crudController = $("#newcontrollerName").val();
			$("#crudTbl").html("<tr><th>Field Name</th><th>Type</th></tr><tr><td>ID</td><td>INT(255), Auto Increment, Primary Key</td></tr>");
			Module.openPopUp('scaffoldForm');
		}
		else
		{
			$('#controllersFeeder').html('Processing...');
			$.ajax({
				type : 'POST',
				url : '<?=$baseUrl;?>/Hanuman/modules/addcontroller',
				data : 'moduleName=' + selectedModule + '&newControllerName=' + $("#newcontrollerName").val() + '&crud=' + $("#crud").is(":checked"),
				success : function(jsonObj)
				{
					if (jsonObj.success)
					{
						$('#controllersFeeder').html('Created successfully');
						$("#newcontrollerName").val('');
						Module.getControllers();
					}
					else
					{
						$('#controllersFeeder').html(jsonObj.message);		
					}
				}
			});	
		}
	},
	'delController' : function()
	{
		$('#controllersFeeder').html('Processing...');
		$.ajax({
			type : 'POST',
			url : '<?=$baseUrl;?>/Hanuman/modules/delcontroller',
			data : 'moduleName=' + selectedModule + '&controllerName=' + $("#controllerSelect").val(),
			success : function(jsonObj)
			{
				if (jsonObj.success)
				{
					$('#controllersFeeder').html('Deleted successfully');
					Module.getControllers();
				}
				else
				{
					$('#controllersFeeder').html(jsonObj.message);		
				}
			}
		});	
	},
	'editController' : function()
	{
	
	},
	'addModel' : function()
	{
		$('#modelsFeeder').html('Processing...');
		$.ajax({
			type : 'POST',
			url : '<?=$baseUrl;?>/Hanuman/modules/addmodel',
			data : 'moduleName=' + selectedModule + '&newModelName=' + $("#newModelName").val(),
			success : function(jsonObj)
			{
				if (jsonObj.success)
				{
					$('#modelsFeeder').html('Created successfully');
					$("#newModelName").val('');
					Module.getModels();
				}
				else
				{
					$('#modelsFeeder').html(jsonObj.message);		
				}
			}
		});	
	},
	'delModel' : function()
	{
		var res = confirm("Are you sure?");
		if (res)
		{
			$('#modelsFeeder').html('Processing...');
			$.ajax({
				type : 'POST',
				url : '<?=$baseUrl;?>/Hanuman/modules/delmodel',
				data : 'moduleName=' + selectedModule + '&modelName=' + $("#modelsSelect").val(),
				success : function(jsonObj)
				{
					if (jsonObj.success)
					{
						$('#modelsFeeder').html('Deleted successfully');
						Module.getModels();
					}
					else
					{
						$('#modelsFeeder').html(jsonObj.message);
					}
				}
			});	
		}
	},
	'editModel' : function()
	{
	
	},
	'addField' : function()
	{
		var newField = $("#newField").val();
		var select = '<select id="'+ newField +'TypeSelect">';
		select += '<option>VARCHAR(255)</option>';
		select += '<option>INT(255)</option>';
		select += '<option>TEXT</option>';
		select += "</select>";
		var jsonEntity = {'name' : newField, 'type' : 'VARCHAR(255)'};
		Module.fields.push(jsonEntity);
		$("#crudTbl").append("<tr><td>"+ newField +"</td><td>" + select + "</td></tr>");
		$("#newField").val('');
	},
	'closePopUp' : function(id)
	{
		$("#" + id).hide();
	},
	'openPopUp' : function(id)
	{
		$("#" + id).show();
	},
	'generateCrud' : function()
	{
		for (var i = 0; i < Module.fields.length; i++)
		{
			if (Module.fields[i].name != 'ID')
			{
				Module.fields[i].type = $("#" + Module.fields[i].name + "TypeSelect").val();
			}
			alert(Module.fields[i].name + ' ' + Module.fields[i].type);
		}
	}
};

$(document).ready(function(){
	Module.getControllers();
	Module.getModels();
})
</script>

<style>
.center {
    float: none;
    margin-left: auto;
    margin-right: auto;
	text-align: center;
}
</style>
<div class="span7 center">
	Selected Module: <b><?=$selectedModule;?></b>
	<br /><br />
	<form action="" onSubmit="return false;" class="form-search">
		Controller name: <input type="text" name="newcontrollerName" id="newcontrollerName" class="input-medium" /> 
		<input class="btn" type="submit" value="Generate" onClick="Module.addController();" /><br />
		<label class="checkbox">
			<input id="crud" type="checkbox"> Create CRUD scaffold
		</label>
		<br /><br />
		Controller name: <select id="controllerSelect" name="controllerSelect"></select> 
		<input class="btn" type="submit" value="Delete" onClick="Module.delController();" />
		<input class="btn" type="submit" value="Edit" onClick="Module.editController();" />
		<div id="controllersFeeder">Loading...</div>
	</form>
	<br /><br />
	<form action="" onSubmit="return false;" class="form-search">
		Model name: <input type="text" name="newModelName" id="newModelName" class="input-medium" /> 
		<input class="btn" type="submit" value="Generate" onClick="Module.addModel();" />
		<br /><br />
		Model name: <select id="modelsSelect" name="modelsSelect"></select> 
		<input class="btn" type="submit" value="Delete" onClick="Module.delModel();" />
		<input class="btn" type="submit" value="Edit" onClick="Module.editModel();" />
		<br />
		<div id="modelsFeeder">Loading...</div>
	</form>
	<br /><br />
	<a href="http://raspi1/hanumanTests/hanumanTest1/public/Hanuman/modules"><i class="icon-backward"></i></a>
</div>

<div style="display: none; position: fixed; top: 60px; width: 100%;" id="scaffoldForm">
	<center>
		<div style="margin: 0 auto; border: 1px solid black; background-color: white; width: 600px; height: 500px; overflow-y: scroll;">
			<table id="crudTbl" class="table">
				<tr>
					<th>
					Field Name
					</th>
					<th>
					Type
					</th>
				</tr>
				<tr>
					<td>
						ID
					</td>
					<td>
						INT(255), Auto Increment, Primary Key
					</td>
				</tr>
			</table>
			<form action="" onSubmit="return false;" class="form-search">
				<input class="input-medium" type="text" id="newField" /> <input onClick="Module.addField();" class="btn" type="button" value="Add Field" />
				<br /><br />
				<input onClick="Module.generateCrud();" class="btn" type="button" value="Generate" /> <input onClick="Module.closePopUp('scaffoldForm');" class="btn" type="button" value="Cancel" />
			</form>
		</div>
	<center>
</div>
